Market/Models/Productos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Market.Models
{
    public class Productos
    {
        //[Key]
        [Display(Name = "Producto")]
        public int Id { get; set; }

        //[Required]
        [Index(IsUnique = true)]
        [StringLength(15)]
        [Display(Name = "Codigo de Producto")]
        public string Codigo { get; set; }

        [Required]
        [StringLength(75)]
        public string Nombre { get; set; }

        [Required]
        public bool Estado { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Creacion")]
        public DateTime FechaCreacion { get; set; }

        [Display(Name = "Unidad Medida")]
        public int UnidadMedidaId { get; set; } // Llave Foranea

        [Display(Name = "Clasificacion")]
        public int ClasificacionProductoId { get; set; } // Llave Foranea

        [ForeignKey("UnidadMedidaId")]
        public UnidadMedidas UnidadMedidas { get; set; }

        [ForeignKey("ClasificacionProductoId")]
        public ClasificacionProductos ClasificacionProductos { get; set; }

        [Required]
        public double Precio { get; set; }
    }
}

Market/Controllers/ClasificacionProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Market.DataBase;
using Market.Models;

namespace Market.Controllers
{
    public class ClasificacionProductosController : Controller
    {
        private MarketContext db = new MarketContext();

        // GET: ClasificacionProductos
        public ActionResult Index()
        {
            return View(db.TClasificacionProductos.ToList());
        }

        // GET: ClasificacionProductos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClasificacionProductos clasificacionProductos = db.TClasificacionProductos.Find(id);
            if (clasificacionProductos == null)
            {
                return HttpNotFound();
            }
            return View(clasificacionProductos);
        }

        // GET: ClasificacionProductos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClasificacionProductos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Codigo,Clasificacion,Estado")] ClasificacionProductos clasificacionProductos)
        {
            if (ModelState.IsValid)
            {
                db.TClasificacionProductos.Add(clasificacionProductos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(clasificacionProductos);
        }

        // GET: ClasificacionProductos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClasificacionProductos clasificacionProductos = db.TClasificacionProductos.Find(id);
            if (clasificacionProductos == null)
            {
                return HttpNotFound();
            }
            return View(clasificacionProductos);
        }

        // POST: ClasificacionProductos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Codigo,Clasificacion,Estado")] ClasificacionProductos clasificacionProductos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clasificacionProductos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(clasificacionProductos);
        }

        // GET: ClasificacionProductos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClasificacionProductos clasificacionProductos = db.TClasificacionProductos.Find(id);
            if (clasificacionProductos == null)
            {
                return HttpNotFound();
            }
            return View(clasificacionProductos);
        }

        // POST: ClasificacionProductos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClasificacionProductos clasificacionProductos = db.TClasificacionProductos.Find(id);
            db.TClasificacionProductos.Remove(clasificacionProductos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Market/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Market.DataBase;
using Market.Models;

namespace Market.Controllers
{
    public class ProductosController : Controller
    {
        private MarketContext db = new MarketContext();

        // GET: Productos
        public ActionResult Index()
        {
            var tProductos = db.TProductos.Include(p => p.ClasificacionProductos).Include(p => p.UnidadMedidas);
            return View(tProductos.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.TProductos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            ViewBag.ClasificacionProductoId = new SelectList(db.TClasificacionProductos, "Id", "Codigo");
            ViewBag.UnidadMedidaId = new SelectList(db.TUnidadMedidas, "Id", "Codigo");
            return View();
        }

        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Codigo,Nombre,Estado,FechaCreacion,UnidadMedidaId,ClasificacionProductoId,Precio")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                db.TProductos.Add(productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClasificacionProductoId = new SelectList(db.TClasificacionProductos, "Id", "Codigo", productos.ClasificacionProductoId);
            ViewBag.UnidadMedidaId = new SelectList(db.TUnidadMedidas, "Id", "Codigo", productos.UnidadMedidaId);
            return View(productos);
        }

        // GET: Productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.TProductos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClasificacionProductoId = new SelectList(db.TClasificacionProductos, "Id", "Codigo", productos.ClasificacionProductoId);
            ViewBag.UnidadMedidaId = new SelectList(db.TUnidadMedidas, "Id", "Codigo", productos.UnidadMedidaId);
            return View(productos);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Codigo,Nombre,Estado,FechaCreacion,UnidadMedidaId,ClasificacionProductoId,Precio")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClasificacionProductoId = new SelectList(db.TClasificacionProductos, "Id", "Codigo", productos.ClasificacionProductoId);
            ViewBag.UnidadMedidaId = new SelectList(db.TUnidadMedidas, "Id", "Codigo", productos.UnidadMedidaId);
            return View(productos);
        }

        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.TProductos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Productos productos = db.TProductos.Find(id);
            db.TProductos.Remove(productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Market/Controllers/UnidadMedidasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Market.DataBase;
using Market.Models;

namespace Market.Controllers
{
    public class UnidadMedidasController : Controller
    {
        private MarketContext db = new MarketContext();

        // GET: UnidadMedidas
        public ActionResult Index()
        {
            return View(db.TUnidadMedidas.ToList());
        }

        // GET: UnidadMedidas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnidadMedidas unidadMedidas = db.TUnidadMedidas.Find(id);
            if (unidadMedidas == null)
            {
                return HttpNotFound();
            }
            return View(unidadMedidas);
        }

        // GET: UnidadMedidas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UnidadMedidas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Codigo,Descripcion,Estado")] UnidadMedidas unidadMedidas)
        {
            if (ModelState.IsValid)
            {
                db.TUnidadMedidas.Add(unidadMedidas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(unidadMedidas);
        }

        // GET: UnidadMedidas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnidadMedidas unidadMedidas = db.TUnidadMedidas.Find(id);
            if (unidadMedidas == null)
            {
                return HttpNotFound();
            }
            return View(unidadMedidas);
        }

        // POST: UnidadMedidas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Codigo,Descripcion,Estado")] UnidadMedidas unidadMedidas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(unidadMedidas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(unidadMedidas);
        }

        // GET: UnidadMedidas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UnidadMedidas unidadMedidas = db.TUnidadMedidas.Find(id);
            if (unidadMedidas == null)
            {
                return HttpNotFound();
            }
            return View(unidadMedidas);
        }

        // POST: UnidadMedidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UnidadMedidas unidadMedidas = db.TUnidadMedidas.Find(id);
            db.TUnidadMedidas.Remove(unidadMedidas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Market/Views/Productos/Create.cshtml
@model Market.Models.Productos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Productos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadMedidaId, "UnidadMedidaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UnidadMedidaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnidadMedidaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasificacionProductoId, "ClasificacionProductoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClasificacionProductoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClasificacionProductoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Market/Views/Productos/Delete.cshtml
@model Market.Models.Productos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClasificacionProductos.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClasificacionProductos.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedidas.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedidas.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Market/Views/Productos/Details.cshtml
@model Market.Models.Productos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClasificacionProductos.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClasificacionProductos.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedidas.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedidas.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Market/Views/Productos/Edit.cshtml
@model Market.Models.Productos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Productos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadMedidaId, "UnidadMedidaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UnidadMedidaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnidadMedidaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasificacionProductoId, "ClasificacionProductoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClasificacionProductoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClasificacionProductoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Market/Views/Productos/Index.cshtml
@model IEnumerable<Market.Models.Productos>

@{
    ViewBag.Title = "Index";
}

<h2 class= "text-center">Productos</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create") | 
    @Html.ActionLink("Ver Clasificacion de Productos", "Index", "ClasificacionProductos") | 
    @Html.ActionLink("Ver Unidad de Medidas", "Index", "UnidadMedidas")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClasificacionProductos.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnidadMedidas.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ClasificacionProductos.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnidadMedidas.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaCreacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new { @class = "btn btn-warning" })
        </td>
    </tr>
}

</table>